//@codekit-append "undomanager.js"
//@codekit-append "chosen/chosen.jquery.min.js"
//@codekit-append "panels.admin.js"
//@codekit-append "panels.admin.panels.js"
//@codekit-append "panels.admin.grid.js"
//@codekit-append "panels.admin.prebuilt.js"
//@codekit-append "panels.admin.tooltip.js"
//@codekit-append "panels.admin.styles.js"